export const styles = {
  mapSection: {
    marginTop: "2rem",
    borderRadius: "1.25rem",
    overflow: "hidden",
    background: "linear-gradient(160deg,#0d1b2e 0%,#0a1628 60%,#0d2240 100%)",
    border: "1px solid rgba(99,179,237,0.15)",
    boxShadow: "0 8px 40px rgba(0,0,0,0.5)",
  },
  mapHeader: {
    padding: "1.75rem 2rem 0",
  },
  eyebrow: {
    fontSize: "0.65rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#63b3ed",
    fontWeight: 600,
    display: "block",
    marginBottom: "0.4rem",
  },
  mapTitle: {
    margin: "0 0 0.5rem",
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "#fff",
  },
  mapSubtitle: {
    margin: "0 0 1.25rem",
    fontSize: "0.82rem",
    color: "rgba(255,255,255,0.45)",
    lineHeight: 1.55,
  },
  boardWrap: {
    position: "relative",
    width: "100%",
    height: "420px",
    overflow: "hidden",
  },
  branchSvg: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    pointerEvents: "none",
  },
  node: {
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.2rem",
    padding: "0.55rem 0.85rem",
    borderRadius: "999px",
    backdropFilter: "blur(6px)",
    transition: "background 0.25s, border 0.25s, transform 0.2s, box-shadow 0.25s",
    fontFamily: "inherit",
    textAlign: "center",
    minWidth: "90px",
    maxWidth: "130px",
  },
  nodeTag: {
    fontSize: "0.55rem",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.45)",
    fontWeight: 600,
  },
  nodeLabel: {
    fontSize: "0.7rem",
    color: "#fff",
    fontWeight: 600,
    lineHeight: 1.3,
  },
  drawer: {
    position: "absolute",
    bottom: "1rem",
    right: "1rem",
    width: "240px",
    maxHeight: "calc(100% - 2rem)",
    background: "rgba(13,27,46,0.92)",
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(99,179,237,0.2)",
    borderRadius: "1rem",
    padding: "1rem",
    cursor: "pointer",
    transition: "width 0.3s",
    overflow: "hidden",
    boxShadow: "0 4px 24px rgba(0,0,0,0.5)",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  drawerExpanded: {
    width: "320px",
    cursor: "default",
  },
  drawerHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "0.5rem",
    marginBottom: "0.25rem",
    flexShrink: 0,
  },
  drawerBody: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    minHeight: 0,
  },
  drawerBodyExpanded: {
    overflowY: "auto",
    paddingRight: "0.2rem",
  },
  drawerTitle: {
    margin: 0,
    fontSize: "0.95rem",
    fontWeight: 700,
    color: "#fff",
  },
  drawerToggle: {
    background: "rgba(99,179,237,0.15)",
    border: "1px solid rgba(99,179,237,0.3)",
    borderRadius: "6px",
    color: "#63b3ed",
    fontSize: "0.65rem",
    fontWeight: 600,
    padding: "0.25rem 0.5rem",
    cursor: "pointer",
    whiteSpace: "nowrap",
    letterSpacing: "0.05em",
    fontFamily: "inherit",
  },
  drawerAssignment: {
    fontSize: "0.72rem",
    color: "rgba(255,255,255,0.6)",
    lineHeight: 1.5,
    margin: "0 0 0.25rem",
  },
  radarWrap: {
    width: "100%",
    height: "130px",
    marginBottom: "0.25rem",
    flexShrink: 0,
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(5,1fr)",
    gap: "0.3rem",
    marginBottom: "0.25rem",
    flexShrink: 0,
  },
  metricCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: "rgba(255,255,255,0.05)",
    borderRadius: "6px",
    padding: "0.3rem 0.2rem",
  },
  metricLabel: {
    fontSize: "0.5rem",
    color: "rgba(255,255,255,0.4)",
    marginBottom: "0.15rem",
    textAlign: "center",
  },
  metricValue: {
    fontSize: "0.8rem",
    color: "#63b3ed",
    fontWeight: 700,
  },
  drawerHint: {
    fontSize: "0.62rem",
    color: "rgba(255,255,255,0.3)",
    margin: 0,
    textAlign: "center",
  },
  expandedCopy: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    marginTop: "0.25rem",
    paddingBottom: "0.1rem",
  },
  expandedHeading: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#fff",
    margin: "0 0 0.35rem",
    letterSpacing: "0.04em",
  },
  expandedList: {
    margin: 0,
    paddingLeft: "1.1rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.3rem",
  },
  expandedItem: {
    fontSize: "0.68rem",
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.5,
  },
  expandedText: {
    fontSize: "0.68rem",
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.5,
    margin: 0,
  },
};

export const chatStyles = {
  wrap: {
    marginTop: "1.75rem",
    borderRadius: "1.25rem",
    background: "linear-gradient(160deg,#0d1b2e 0%,#0a1628 60%,#0d2240 100%)",
    border: "1px solid rgba(99,179,237,0.15)",
    boxShadow: "0 8px 40px rgba(0,0,0,0.5)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    padding: "1.5rem 1.75rem 0.75rem",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  eyebrow: {
    fontSize: "0.65rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#63b3ed",
    fontWeight: 600,
    display: "block",
    marginBottom: "0.35rem",
  },
  title: {
    margin: "0 0 0.3rem",
    fontSize: "1.2rem",
    fontWeight: 700,
    color: "#fff",
  },
  subtitle: {
    margin: 0,
    fontSize: "0.78rem",
    color: "rgba(255,255,255,0.4)",
    lineHeight: 1.5,
  },
  feed: {
    padding: "1rem 1.25rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.7rem",
    maxHeight: "260px",
    overflowY: "auto",
  },
  bubble: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.55rem",
    maxWidth: "80%",
  },
  bubbleBot: {
    alignSelf: "flex-start",
  },
  bubbleUser: {
    alignSelf: "flex-end",
    flexDirection: "row-reverse",
  },
  avatar: {
    flexShrink: 0,
    width: "26px",
    height: "26px",
    borderRadius: "50%",
    background: "linear-gradient(135deg,#2b6cb0,#63b3ed)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.65rem",
    fontWeight: 700,
    color: "#fff",
    lineHeight: 1,
    paddingTop: "1px",
  },
  bubbleText: {
    margin: 0,
    padding: "0.55rem 0.85rem",
    borderRadius: "1rem",
    fontSize: "0.8rem",
    lineHeight: 1.55,
    color: "rgba(255,255,255,0.88)",
    background: "rgba(255,255,255,0.07)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  typing: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    minHeight: "1.2rem",
  },
  dot: {
    display: "inline-block",
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    background: "#63b3ed",
    animation: "blink 1.2s infinite ease-in-out",
  },
  inputRow: {
    display: "flex",
    gap: "0.6rem",
    padding: "0.85rem 1.25rem 1.1rem",
    borderTop: "1px solid rgba(255,255,255,0.06)",
    alignItems: "flex-end",
  },
  textarea: {
    flex: 1,
    resize: "none",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(99,179,237,0.2)",
    borderRadius: "0.75rem",
    color: "#fff",
    fontSize: "0.82rem",
    padding: "0.6rem 0.9rem",
    fontFamily: "inherit",
    lineHeight: 1.5,
    outline: "none",
    minHeight: "38px",
  },
  sendBtn: {
    background: "linear-gradient(135deg,#2b6cb0,#63b3ed)",
    border: "none",
    borderRadius: "0.75rem",
    color: "#fff",
    fontWeight: 700,
    fontSize: "0.78rem",
    padding: "0.6rem 1.1rem",
    cursor: "pointer",
    fontFamily: "inherit",
    letterSpacing: "0.04em",
    transition: "opacity 0.2s",
    whiteSpace: "nowrap",
  },
};
